import { icon } from '../components/icons.js';
import { loadStudy } from '../core/study.js';
import { coursesForLevel } from '../data/courses/index.js';
export function renderHomePage(container){
 const study=loadStudy(),completed=study.read,next=coursesForLevel(study.level).find(l=>!completed.includes(l.id));
 const topics=[['🚀','Gerak & Gaya','Kenapa bola bisa bergerak?','dynamics','peach'],['💡','Cahaya & Warna','Ke mana cahaya pergi?','optics','yellow'],['🧲','Listrik & Magnet','Temukan tarikan tak terlihat.','electricity','pink'],['🪐','Bumi & Antariksa','Ada apa di luar sana?','astrophysics','lavender']];
 container.innerHTML=`<div class="home-shell content-wrap"><section class="welcome-hero"><div class="hero-copy"><span class="eyebrow"><span class="little-spark">✦</span> RASA INGIN TAHU DIMULAI DI SINI</span><h1>Pahami dunia.<br><em>Temukan fisikanya.</em></h1><p>Dari pertanyaan pertama sampai teori yang mendalam. Jelajahi fisika melalui konsep, perhitungan, dan percobaan—untuk pelajar SD hingga pengajar.</p><div class="hero-actions"><a class="btn-primary" href="#/learn">Pilih jalur belajar ${icon('arrow')}</a><a class="btn-secondary" href="#/simulations">${icon('flask')} Buka laboratorium</a></div><div class="hero-reassurance"><span>${icon('check',16)} Belajar sesuai tahapmu</span><span>${icon('check',16)} Bebas iklan</span></div></div><div class="discovery-art" aria-label="Ilustrasi buku, planet, dan penemuan fisika" role="img"><div class="art-orbit orbit-one"></div><div class="art-orbit orbit-two"></div><span class="art-star star-one">✦</span><span class="art-star star-two">✦</span><span class="art-star star-three">✧</span><div class="art-planet"><span></span></div><div class="art-book"><div class="book-left"><i></i><i></i><i></i></div><div class="book-right"><i></i><i></i><i></i></div></div><div class="art-rocket">🚀</div><div class="art-note note-gravity">🍎<span>Kenapa benda<br><strong>jatuh ke bawah?</strong></span></div><div class="art-note note-light">☀️<span>Satu pertanyaan,<br><strong>banyak penemuan!</strong></span></div><div class="art-dot dot-one"></div><div class="art-dot dot-two"></div></div></section>
 <section class="learning-strip"><span class="strip-icon">${icon('book',26)}</span><div><strong>${completed.length?'Selamat datang kembali, penjelajah!':'Sedikit demi sedikit, jadi makin mengerti.'}</strong><p>${completed.length?`${completed.length} pelajaran sudah kamu tandai selesai. Ayo lanjutkan rasa ingin tahumu.`:'Mulai dari satu pelajaran kecil. Baca, coba, lalu ceritakan yang kamu temukan.'}</p></div><a href="${next?`#/lesson/${next.id}?level=${study.level}`:'#/learn'}">${completed.length?'Lanjut belajar':'Pilih jalur belajar'} ${icon('arrow',18)}</a></section>
 <section class="home-section"><div class="section-heading"><div><span class="eyebrow">JELAJAHI DUNIAMU</span><h2>Hari ini, mau tahu apa?</h2></div><a class="text-link" href="#/explore">Semua topik ${icon('arrow',18)}</a></div><div class="topic-grid">${topics.map(([emoji,title,desc,id,color],i)=>`<a class="topic-tile ${color}" href="#/explore?domain=${id}"><span class="topic-illustration">${emoji}</span><span class="topic-number">0${i+1}</span><h3>${title}</h3><p>${desc}</p><span class="tile-arrow">${icon('arrow')}</span></a>`).join('')}</div></section>
 <section class="home-section lab-feature"><div class="lab-preview"><span class="lab-label">COBA. AMATI. TEMUKAN.</span><div class="mini-trajectory"><span class="launch-ball"></span><i></i><i></i><i></i><i></i><i></i><span class="trajectory-ground"></span></div><span class="preview-caption">Apa yang terjadi jika sudutnya berubah?</span></div><div><span class="eyebrow">LABORATORIUM INTERAKTIF</span><h2>Kamu yang mengendalikan percobaannya.</h2><p>Geser tombol, ubah gaya, atau buat rangkaian listrik. Lihat langsung bagaimana satu perubahan memberi hasil yang berbeda.</p><a class="btn-primary" href="#/simulations?sim=projectile">Ayo bereksperimen ${icon('arrow')}</a><span class="lab-footnote">13 lab interaktif · Bisa dicoba berulang kali</span></div></section>
 <section class="home-section"><div class="section-heading"><div><span class="eyebrow">LANGKAH KECIL, PENGETAHUAN BESAR</span><h2>Temukan jalur belajarmu.</h2></div></div><div class="journey-grid">${[['sd','🌱','Dasar & intuisi','SD','Mengamati dunia lewat cerita dan aktivitas.'],['smp','🔎','Konsep & pengukuran','SMP','Menghubungkan ide dengan pengukuran.'],['sma','⚡','Analisis & penerapan','SMA','Memahami model, rumus, dan alasannya.'],['university','🪐','Teori & pemodelan','Universitas','Menelusuri teori dan model lebih dalam.'],['educator','📚','Mengajar & mendampingi','Pengajar','Merancang kegiatan dan asesmen bermakna.']].map(([id,emoji,title,level,desc])=>`<a class="journey-card" href="#/learn?level=${id}"><span>${emoji}</span><span class="level-label">${level}</span><h3>${title}</h3><p>${desc}</p><span class="text-link">Mulai jelajah ${icon('arrow',16)}</span></a>`).join('')}</div></section>
 <section class="curiosity-banner"><span>✦</span><div><h2>Pertanyaanmu adalah awal penemuan.</h2><p>Belum tahu jawabannya? Tidak apa-apa. Kita pelajari bersama.</p></div><button class="btn-secondary" id="home-search">${icon('search')} Cari rasa ingin tahumu</button></section><section class="support-banner"><div><h2>Suka belajar di Phsyco?</h2><p>Bantu ruang belajar ini terus tumbuh. Dukungan sukarela, belajar tetap gratis.</p></div><a class="btn" href="#/dukung">Dukung Phsyco →</a></section></div>`;
 container.querySelector('#home-search').addEventListener('click',()=>window.dispatchEvent(new CustomEvent('open-search')));
}
