import {topicLabel} from '../data/topic-labels.js';
import {COURSES,LEVELS,coursesForLevel,findCourse} from '../data/courses/index.js';
import {loadStudy,setStudyLevel,exportStudy,resetStudy} from '../core/study.js';
import {renderLessonPage} from './lesson-page.js';
import {icon} from '../components/icons.js';
import {escapeHTML as esc} from '../core/html.js';
import {PHYSICS_DOMAINS} from '../data/domains.js';
export function renderLearnPage(container,params={}){
 if(params.lesson)return renderLessonPage(container,{id:params.lesson,level:params.level});
 let state=loadStudy(),level=LEVELS.find(l=>l.id===params.level)||LEVELS.find(l=>l.id===state.level),query='',all=params.all==='1';
 setStudyLevel(level.id);
 function render(){
  const path=coursesForLevel(level.id),list=(all?COURSES:path).filter(c=>`${c.title} ${c.topics.join(' ')} ${c.topics.map(topicLabel).join(' ')}`.toLowerCase().includes(query.toLowerCase())),read=path.filter(c=>state.read.includes(c.id)).length,passed=path.filter(c=>state.passed.includes(c.id)).length,next=path.find(c=>!state.read.includes(c.id));
  container.innerHTML=`<div class="content-wrap study-hub"><header class="page-heading"><span class="eyebrow">RUANG BELAJAR</span><h1>Belajar dengan caramu.</h1><p>Pilih jenjang, pahami konsep, lalu uji pemahamanmu. Semua jalur dapat dijelajahi tanpa terkunci.</p></header><div class="level-tabs" role="group" aria-label="Jenjang belajar">${LEVELS.map(l=>`<button data-lvl-id="${l.id}" aria-pressed="${l.id===level.id}" class="level-tab ${l.id===level.id?'selected':''}"><span>${l.icon}</span>${l.label}</button>`).join('')}</div>
  <section class="study-overview"><div><span class="eyebrow">${level.label.toUpperCase()}</span><h2>${level.title}</h2><p>${level.description}</p>${next?`<a class="btn-primary" href="#/lesson/${next.id}?level=${level.id}">${read?'Lanjutkan belajar':'Mulai pelajaran pertama'} ${icon('arrow',18)}</a>`:'<p class="completion-message">Semua materi pada jalur ini sudah kamu baca. Tinjau latihan dan catatanmu kapan saja.</p>'}</div><div class="study-progress-card"><div class="progress-label"><strong>${read}<span> / ${path.length}</span></strong><span>pelajaran dibaca</span></div><progress value="${read}" max="${path.length}" aria-label="Progres membaca"></progress><p>${icon('check',16)} ${passed} latihan dijawab benar</p><small>Catatan mandiri di perangkat ini. Hasil latihan singkat bukan sertifikasi penguasaan.</small></div></section>
  <div class="study-workspace"><section class="lesson-catalog"><div class="catalog-toolbar"><h2>${all?'Semua materi':'Materi untuk jenjangmu'}</h2><button class="text-button" id="toggle-all">${all?'Kembali ke jalurku':'Lihat semua materi'}</button></div><label class="field-search">${icon('search')}<input id="lesson-search" type="search" aria-label="Cari pelajaran" placeholder="Cari topik di jalur ini..." value="${esc(query)}"></label><p class="result-count">${list.length} pelajaran · ${all?'Seluruh jenjang':level.label}</p><div class="lesson-cards">${list.map((c,i)=>`<a class="study-card" href="#/lesson/${c.id}?level=${level.id}"><span class="study-card-number">${String(i+1).padStart(2,'0')}</span><div><span class="card-kicker">${esc(PHYSICS_DOMAINS.find(d=>d.id===c.domainId)?.indonesianName||c.domainId)}</span><h3>${esc(c.title)}</h3><p>${esc(c.intuition)}</p><div class="card-meta"><span>${c.minutes} menit</span><span>${c.topics.length} pokok bahasan</span>${state.read.includes(c.id)?'<span class="done-mark">✓ Dibaca</span>':''}${state.passed.includes(c.id)?'<span class="done-mark">✓ Latihan</span>':''}</div></div><span class="study-card-arrow">${icon('arrow')}</span></a>`).join('')||'<div class="empty-state"><h3>Materi belum ditemukan</h3><p>Coba kata yang lebih singkat atau tampilkan semua materi.</p><button class="btn-secondary" id="reset-lesson-search">Reset pencarian</button></div>'}</div></section>
  <aside class="study-tools"><div class="tool-card"><span class="tool-icon">${icon('flask',24)}</span><h3>Uji lewat percobaan</h3><p>Hubungkan pelajaran dengan 13 model interaktif.</p><a href="#/simulations">Buka laboratorium ${icon('arrow',16)}</a></div><div class="tool-card"><span class="tool-icon">${icon('graph',24)}</span><h3>Lihat keterkaitannya</h3><p>Telusuri hubungan konsep, besaran dan hukum.</p><a href="#/graph">Buka peta konsep ${icon('arrow',16)}</a></div><div class="tool-card"><h3>Catatan belajarmu</h3><p>Simpan catatan di setiap pelajaran. Unduh salinan progres dan catatanmu.</p><button class="btn-secondary" id="export-study">Unduh catatan</button><details class="reset-progress"><summary>Kelola progres</summary><p>Penghapusan berlaku pada progres dan catatan versi ini di perangkat ini.</p><button class="text-button" id="reset-study">Hapus progres & catatan</button><div id="reset-confirm" hidden><p>Hapus seluruh catatan dan progres? Tindakan ini tidak dapat dibatalkan.</p><button class="btn-secondary" id="cancel-reset">Batal</button><button class="btn-primary" id="confirm-reset">Ya, hapus</button></div></details><p role="status" id="study-status"></p></div><a class="teacher-callout" href="#/learn?level=educator">${icon('book',22)}<span><strong>Ruang pengajar</strong><small>Modul ajar, asesmen & aktivitas</small></span>${icon('arrow',18)}</a></aside></div></div>`;
  container.querySelectorAll('[data-lvl-id]').forEach(b=>b.addEventListener('click',()=>location.hash=`#/learn?level=${b.dataset.lvlId}`));
  container.querySelector('#toggle-all').addEventListener('click',()=>{all=!all;render();container.querySelector('#toggle-all').focus();});
  const input=container.querySelector('#lesson-search');input.addEventListener('input',()=>{const position=input.selectionStart;query=input.value;render();const fresh=container.querySelector('#lesson-search');fresh.focus();if(fresh.type==='text')fresh.setSelectionRange(position,position);});
  container.querySelector('#reset-lesson-search')?.addEventListener('click',()=>{query='';render();});
  container.querySelector('#export-study').addEventListener('click',()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([exportStudy()],{type:'application/json'}));a.href=url;a.download='asadin-physics-catatan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  container.querySelector('#reset-study').addEventListener('click',()=>container.querySelector('#reset-confirm').hidden=false);
  container.querySelector('#cancel-reset').addEventListener('click',()=>container.querySelector('#reset-confirm').hidden=true);
  container.querySelector('#confirm-reset').addEventListener('click',()=>{if(resetStudy()){state=loadStudy();render();}else container.querySelector('#study-status').textContent='Penyimpanan tidak tersedia. Progres belum dihapus.';});
 }
 render();
}
