import { DEEP_DIVES } from '../data/courses/deep-dives.js';
import { topicLabel } from '../data/topic-labels.js';
import {COURSES,LEVELS,findCourse,coursesForLevel,prerequisiteFor} from '../data/courses/index.js';
import {loadStudy,saveStudy} from '../core/study.js';
import {PHYSICS_ENTITIES} from '../data/entities.js';
import {icon} from '../components/icons.js';
import {escapeHTML as esc} from '../core/html.js';
export function renderLessonPage(container,params={}){
 const course=findCourse(params.id);if(!course){container.innerHTML='<div class="content-wrap empty-state"><h1>Pelajaran tidak ditemukan</h1><a class="btn-primary" href="#/learn">Pilih materi belajar</a></div>';return;}
 let state=loadStudy(),level=LEVELS.find(l=>l.id===params.level)||LEVELS.find(l=>l.id===course.level),activeDepth=(level.id==='university'||level.id==='educator')?'advanced':level.id==='sd'?'simple':'standard';
 const path=coursesForLevel(level.id),index=path.findIndex(c=>c.id===course.id),next=index>=0?path[index+1]:null,previous=prerequisiteFor(course,level.id),related=PHYSICS_ENTITIES.filter(e=>e.domainId===course.domainId).slice(0,5);
 const options=[course.answer,...course.distractors];const rotate=[...course.id].reduce((s,c)=>s+c.charCodeAt(0),0)%options.length;options.push(...options.splice(0,rotate));
 let answered=null;
 const paragraphs=text=>text.split(/(?<=[.!?]) (?=[A-ZÀ-Ý“])/).reduce((out,sentence,index)=>{const n=Math.floor(index/3);out[n]=(out[n]||'')+(out[n]?' ':'')+sentence;return out;},[]).map(p=>`<p>${esc(p)}</p>`).join('');
 function render(){
 container.innerHTML=`<div class="content-wrap lesson-shell"><nav class="breadcrumb" aria-label="Jejak halaman"><a href="#/learn?level=${level.id}">Belajar</a><span>/</span><a href="#/learn?level=${level.id}">${level.label}</a><span>/</span><span>${esc(course.title)}</span></nav><div class="reader-layout"><aside class="reader-sidebar"><a class="back-link" href="#/learn?level=${level.id}">← Kembali ke jalur belajar</a><span class="eyebrow">DALAM PELAJARAN INI</span><nav aria-label="Bagian pelajaran">${[['intro','Gambaran awal'],['understand','Pahami konsep'],['worked','Contoh terurai'],['activity','Coba & amati'],['practice','Cek pemahaman'],['notes','Catatan saya'],['sources','Sumber bacaan']].map(([id,title])=>`<a href="#" data-scroll="${id}">${title}</a>`).join('')}</nav>${previous?`<div class="prerequisite"><small>Bekal sebelumnya</small><a href="#/lesson/${previous.id}?level=${level.id}">${esc(previous.title)}</a></div>`:''}<button class="btn-secondary print-lesson">Cetak materi</button><button class="text-button" id="copy-lesson-link">Salin tautan pelajaran</button><p class="save-status" role="status" id="share-status"></p></aside><article class="lesson-reader"><header class="reader-header"><div class="reader-meta"><span class="lesson-chip">${level.label}</span><span>${course.minutes} menit</span><span>${course.topics.length} pokok bahasan</span></div><h1>${esc(course.title)}</h1><p>${esc(course.intuition)}</p></header><section id="intro" class="learning-objectives"><h2>Yang akan kamu pelajari</h2><ul>${course.topics.map(t=>`<li>${esc(topicLabel(t))}</li>`).join('')}</ul></section>
 <section id="understand" class="reader-section"><div class="reader-section-heading"><span>01</span><h2>Pahami konsepnya</h2></div><div class="reading-depth" role="group" aria-label="Kedalaman materi">${[['simple','Intuisi'],['standard','Penjelasan'],['advanced','Analisis lanjut'],...(DEEP_DIVES[course.id]?[['deepDive','Pendalaman']]:[])].map(([id,title])=>`<button data-depth="${id}" aria-pressed="${id===activeDepth}">${title}</button>`).join('')}</div><div class="reader-prose" id="depth-content">${activeDepth==='deepDive'?`<h3>${esc(DEEP_DIVES[course.id].title)}</h3>${paragraphs(DEEP_DIVES[course.id].text)}`:paragraphs(activeDepth==='simple'?course.intuition:activeDepth==='advanced'?course.explanation+' '+course.advanced:course.explanation)}</div>${level.id==='sd'&&course.level!=='sd'?'<p class="scope-note">Materi ini berasal dari jalur lanjut. Mulai dari gambaran awal dan pelajari bagian matematika bersama pendamping.</p>':''}</section>
 <section id="worked" class="reader-section"><div class="reader-section-heading"><span>02</span><h2>Contoh terurai</h2></div><div class="worked-example">${paragraphs(course.example)}</div><details class="reflection"><summary>Periksa kembali penalaranmu</summary><p>Besaran apa yang diketahui? Model dan asumsi apa yang digunakan? Periksa satuan, tanda, dan apakah hasilnya masuk akal. Ubah satu kondisi pada contoh, lalu jelaskan hasil yang kamu perkirakan.</p></details></section>
 <section id="activity" class="reader-section"><div class="reader-section-heading"><span>03</span><h2>Coba, amati, jelaskan</h2></div><div class="activity-panel">${icon('flask',25)}<div>${paragraphs(course.activity)}${course.sim?`<a class="btn-secondary" href="#/simulations?sim=${course.sim}">Buka percobaan terkait ${icon('arrow',16)}</a>`:''}</div></div></section>
 <section id="practice" class="reader-section"><div class="reader-section-heading"><span>04</span><h2>Cek pemahaman</h2></div><p class="practice-intro">Pilih jawaban, lalu baca alasannya. Kamu bisa mencoba lagi.</p><fieldset class="lesson-quiz"><legend>${esc(course.question)}</legend>${options.map((option,i)=>`<button class="quiz-option-btn" data-answer="${i}" ${answered!==null?'disabled':''}><span>${String.fromCharCode(65+i)}</span>${esc(option)}</button>`).join('')}<div class="quiz-feedback-box ${answered===null?'':options[answered]===course.answer?'correct':'incorrect'}" role="status" tabindex="-1" ${answered===null?'hidden':''}>${answered===null?'':`<strong>${options[answered]===course.answer?'Tepat!':'Mari periksa lagi.'}</strong><p>${esc(course.reason)}</p><p>Jawaban: ${esc(course.answer)}</p><button class="btn-secondary" id="retry-question">Coba lagi</button>`}</div></fieldset></section>
 <section id="notes" class="reader-section"><div class="reader-section-heading"><span>05</span><h2>Catatan saya</h2></div><label for="lesson-notes">Apa yang baru kamu pahami? Pertanyaan apa yang masih ingin ditelusuri?</label><textarea id="lesson-notes" maxlength="10000" rows="5" placeholder="Tulis dengan kata-katamu sendiri...">${esc(state.notes[course.id]||'')}</textarea><p class="save-status" role="status" id="notes-status">Catatan hanya tersimpan di browser perangkat ini.</p></section>
 ${level.id==='educator'?`<section class="teacher-plan"><span class="eyebrow">PANDUAN PENGAJAR</span><h2>Rencana kegiatan yang dapat diadaptasi</h2><dl><dt>Tujuan</dt><dd>Peserta menjelaskan ${esc(course.topics.map(topicLabel).join(', '))} serta memberi alasan berdasarkan contoh atau data.</dd><dt>Pembuka · 5 menit</dt><dd>Gunakan pertanyaan: ${esc(course.question)} Minta alasan sebelum memberi jawaban.</dd><dt>Eksplorasi · 15 menit</dt><dd>${esc(course.activity)}</dd><dt>Diskusi · 10 menit</dt><dd>Bandingkan prediksi dengan contoh terurai. Minta siswa menyebut asumsi dan satu keterbatasan model.</dd><dt>Asesmen · 5 menit</dt><dd>${esc(course.question)} Kunci: ${esc(course.answer)}. Alasan: ${esc(course.reason)}</dd><dt>Rubrik</dt><dd>0: jawaban belum sesuai; 1: hasil benar tetapi alasan belum lengkap; 2: hasil dan alasan sesuai serta mampu menerapkan pada situasi baru.</dd><dt>Diferensiasi</dt><dd>Dasar: jawaban melalui sketsa atau penjelasan lisan. Menengah: sertakan hitungan/grafik. Lanjut: uji asumsi dan derivasi pada tab analisis.</dd></dl><button class="btn-secondary print-lesson">Cetak modul ajar</button></section>`:''}
 <section id="sources" class="reader-sources"><h2>Sumber & bacaan lanjutan</h2><a href="${esc(course.url)}" target="_blank" rel="noopener noreferrer">${esc(new URL(course.url).hostname)} · Rujukan ${esc(course.title)} ↗</a><p>Penjelasan dan contoh ditulis untuk aplikasi ini. Sumber mendukung konsep dan memberi bacaan lanjutan; cakupan satu pelajaran bukan pengganti seluruh mata kuliah.</p>${related.length?`<h3>Telusuri konsep terkait</h3><div class="resource-links">${related.map(e=>`<a href="#/entity/${e.id}">${esc(e.indonesianName)}</a>`).join('')}</div>`:''}</section>
 <div class="lesson-actions"><button class="btn-secondary" data-complete="${course.id}" aria-pressed="${state.read.includes(course.id)}">${state.read.includes(course.id)?'✓ Sudah dibaca · batalkan':'Tandai sudah dibaca'}</button>${next?`<a class="btn-primary" href="#/lesson/${next.id}?level=${level.id}">Pelajaran berikutnya ${icon('arrow',18)}</a>`:`<a class="btn-primary" href="#/learn?level=${level.id}">Kembali ke jalur</a>`}</div><p role="status" id="reader-save-status"></p></article></div></div>`;
 container.querySelectorAll('[data-scroll]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();container.querySelector(`#${a.dataset.scroll}`).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}));
 container.querySelectorAll('[data-depth]').forEach(b=>b.addEventListener('click',()=>{activeDepth=b.dataset.depth;render();container.querySelector(`[data-depth="${activeDepth}"]`).focus();}));
 container.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{answered=Number(b.dataset.answer);state.attempts[course.id]=(state.attempts[course.id]||0)+1;if(options[answered]===course.answer&&!state.passed.includes(course.id))state.passed.push(course.id);const saved=saveStudy(state);render();if(!saved)container.querySelector('#reader-save-status').textContent='Penyimpanan tidak tersedia; hasil belum tersimpan permanen.';container.querySelector('.quiz-feedback-box').focus({preventScroll:true});container.querySelector('.quiz-feedback-box').scrollIntoView({block:'nearest'});}));
 container.querySelector('#retry-question')?.addEventListener('click',()=>{answered=null;render();container.querySelector('[data-answer]').focus();});
 container.querySelector('[data-complete]').addEventListener('click',()=>{state.read=state.read.includes(course.id)?state.read.filter(id=>id!==course.id):[...state.read,course.id];const saved=saveStudy(state);render();container.querySelector('[data-complete]').focus();if(!saved)container.querySelector('#reader-save-status').textContent='Penyimpanan tidak tersedia; progres belum tersimpan permanen.';});
 const notes=container.querySelector('#lesson-notes');notes.addEventListener('input',()=>{state.notes[course.id]=notes.value;const saved=saveStudy(state);container.querySelector('#notes-status').textContent=saved?'Tersimpan di perangkat ini.':'Penyimpanan tidak tersedia. Salin catatan sebelum menutup halaman.';});
 container.querySelector('#copy-lesson-link').addEventListener('click',async()=>{const output=container.querySelector('#share-status');try{await navigator.clipboard.writeText(location.href);output.textContent='Tautan tersalin. Bagikan melalui pilihanmu.';}catch{output.textContent=`Salin alamat dari bilah browser: ${location.href}`;}});
 container.querySelectorAll('.print-lesson').forEach(b=>b.addEventListener('click',()=>window.print()));
 }
 render();

}
